### PR TITLE
fix: recursive min coverage

### LINKED ISSUE #389: fix: `--min-coverage` does not work when running with `--recursive`
**Description**

Currently if you run `very_good test --min-coverage 100 --recursive` it will go through each package it finds and run the tests. But if any of those packages don't have 100% test coverage there won't be an error displaying that.

Here I am running the command at the root of my project:
image

It finds three packages, which is correct, but all three of them don't have 100% test coverage:
- `umbra_flutter`: image
- `umbra_core`: image
- `umbra_cli`: image

**Steps To Reproduce**

1. Create a repo with two packages, and ensure they don't have full test coverage
2. Run `very_good test --min-coverage 100 --recursive` at the root
3. Tests will succeed but no coverage is reported.

**Expected Behavior**
I expected that I was able to combine these flags together to run all my tests at the highest level and confirm that they all have the coverage I expected.

Related: https://github.com/VeryGoodOpenSource/very_good_cli/issues/383

### PR DESCRIPTION
**Pull request by willhlas**
## Description

Fixes bug where running `--min-coverage` with `--recursive` would not throw error if min coverage was not met.

Closes #389 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by wolfenrain — APPROVED** [review]

File: lib/src/cli/flutter_cli.dart [hunk 1]
```diff
@@ -209,29 +209,30 @@ class Flutter {
           ],
           stdout: stdout ?? noop,
           stderr: stderr ?? noop,
-        ).whenComplete(() {
+        ).whenComplete(() async {
           if (optimizePerformance) {
             File(p.join(cwd, 'test', '.test_runner.dart')).delete().ignore();
           }
+
+          if (collectCoverage) {
```
Comment (felangel) [inline lib/src/cli/flutter_cli.dart:217]: Can we add a test for this fix to ensure it doesn't happen again?

**Review by felangel — CHANGES_REQUESTED** [review]
Can we add a test for this fix to ensure it doesn't happen again?

**Review by renancaraujo — APPROVED** [review]

**Review by felangel — DISMISSED** [review]

**Review by wolfenrain — APPROVED** [review]
