### PR TITLE
fix: flutter_gen breaks current template

### LINKED ISSUE #987: fix: flutter_gen breaks current template
**Description**
After updating to very_good cli v0.20, and running create, it outputs a flutter project that depends on `flutter_gen: any`, so that when you run pub get, the `l10n.dart` errors out.

```bash
Target of URI doesn't exist: 'package:flutter_gen/gen_l10n/app_localizations.dart'.
```

**Steps To Reproduce**

1. Update your very_good_cli to v0.20
2. Create new flutter project
3. Open project in IDE
4. Run `pub get`
5. See error

**Expected Behavior**
Should compile successfully after running pub get

**Additional Context**
The template for the previous version of `very_good_cli` doesn't explicitly add `flutter_gen` to `pubspec.yaml`

### PR DESCRIPTION
**Pull request by wolfenrain**
## Status

**READY**

## Description

This PR does not fix #987 but does mitigate the potential of it happening as much as possible

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: lib/src/commands/create/templates/post_generate_actions.dart [hunk 1]
```diff
@@ -2,35 +2,38 @@ import 'package:mason/mason.dart';
 import 'package:universal_io/io.dart';
 import 'package:very_good_cli/src/cli/cli.dart';
 
-/// Runs `flutter pub get` in the [outputDir].
-Future<void> installDartPackages(
+/// Runs `dart pub get` in the [outputDir].
```
Comment (alestiago) [inline lib/src/commands/create/templates/post_generate_actions.dart:5]:
```suggestion
/// Runs `dart pub get` in the [outputDir].
///
/// Returns `true` is the execution was successful, `false` otherwise.
```

File: lib/src/commands/create/templates/post_generate_actions.dart [hunk 2]
```diff
@@ -2,35 +2,38 @@ import 'package:mason/mason.dart';
...
     );
-    await Flutter.pubGet(cwd: outputDir.path, logger: logger);
-    installDependenciesProgress.complete();
   }
+  return false;
 }
 
-/// Runs `flutter packages get` in the [outputDir].
-Future<void> installFlutterPackages(
+/// Runs `flutter pub get` in the [outputDir].
```
Comment (alestiago) [inline lib/src/commands/create/templates/post_generate_actions.dart:22]:
```suggestion
/// Runs `flutter pub get` in the [outputDir].
///
/// Returns `true` is the execution was successful, `false` otherwise.
```

**Review by alestiago — APPROVED** [review]
LGTM! Hopefully we get to refactor some of the redundancy in the future.

**Review by alestiago — APPROVED** [review]
