### PR TITLE
fix: avoid failure when terminal has no columns

### LINKED ISSUE #866: fix: StdoutException: Could not get terminal size, OS Error: Operation not supported on socket, errno = 102
**Description**
I'm using the `very_good test --coverage` command in a pipeline in Azure Devops, and it's returning this error when trying to write the message in the terminal:

"Thank you for using Very Good Ventures open source tools!
Don't forget to fill out this form to get information on future updates and releases here:
https://verygood.ventures/open-source/cli/subscribe-latest-tool-updates"

**Steps To Reproduce**

1. Install lastest version 1.17.0
2. Run `very_good test --coverage`

**Expected Behavior**

**Screenshots**
image

**Additional Context**
Locally works normally

### PR DESCRIPTION
**Pull request by alestiago**
## Description

Resolves #866 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by erickzanardo — DISMISSED** [review]

File: lib/src/logger_extension.dart [hunk 1]
```diff
@@ -11,13 +20,24 @@ extension LoggerX on Logger {
...
     String? text, {
     required void Function(String?) print,
     int? length,
   }) {
-    final maxLength = length ?? stdout.terminalColumns;
+    late final int maxLength;
+    try {
+      maxLength = length ?? stdout.terminalColumns;
+    } on StdoutException catch (_) {
+      // Not all terminals have a width, so we fallback to a reasonable value.
```
Comment (wolfenrain) [inline lib/src/logger_extension.dart:37]: It is only thrown if the terminal has no stdout, instead we should just check for [hasTerminal](https://api.dart.dev/stable/2.13.3/dart-io/Stdout/hasTerminal.html) and use that as the fallback.

Comment (alestiago) [reply lib/src/logger_extension.dart]: I amended the code. For other readers this information is documented within the `terminalColumns` method:

> If no terminal is attached to stdout, a [StdoutException] is thrown. See [hasTerminal] for more info.

File: lib/src/logger_extension.dart [hunk 2]
```diff
@@ -11,13 +21,25 @@ extension LoggerX on Logger {
...
   }) {
-    final maxLength = length ?? stdout.terminalColumns;
+    late final int maxLength;
+    if (length != null) {
+      maxLength = length;
+    } else if (stdout.hasTerminal) {
+      maxLength = stdout.terminalColumns;
+    } else {
+      maxLength = fallbackStdoutTerminalColumns;
+    }
```
Comment (wolfenrain) [inline lib/src/logger_extension.dart:41]:
```suggestion
    final maxLength = switch (length) {
      == null when stdout.hasTerminal => stdout.terminalColumns,
      == null when !stdout.hasTerminal => fallbackStdoutTerminalColumns,
      _ => length
    };
```

Comment (alestiago) [reply lib/src/logger_extension.dart:41]: I think this is Nit. Tbh, I think the suggestion is less legible. Does it have an impact on performance?

Comment (wolfenrain) [reply lib/src/logger_extension.dart:41]: Then u add a `!` to it

Comment (wolfenrain) [reply lib/src/logger_extension.dart:41]: it is guaranteed to be non-null anyway, but because `hasTerminal` is not a constant value it can't figure that out

**Review by wolfenrain — APPROVED** [review]

File: lib/src/logger_extension.dart [hunk 3]
```diff
@@ -11,13 +21,22 @@ extension LoggerX on Logger {
...
+  ///
+  /// To completely overwrite the width you can use [length].
   void wrap(
     String? text, {
     required void Function(String?) print,
     int? length,
   }) {
-    final maxLength = length ?? stdout.terminalColumns;
+    final maxLength = switch (length) {
+      == null when stdout.hasTerminal => stdout.terminalColumns,
```
Comment (erickzanardo) [inline lib/src/logger_extension.dart:35]: Oh, this is new to me, pretty cool

**Review by erickzanardo — APPROVED** [review]
