### PR TITLE
fix: support ignoring empty globs

### LINKED ISSUE #703: fix: allow specifying an empty string as a Glob
**Description**
When using Very Good CLI 0.12.3 doing:

```sh
very_good packages get -r --ignore=""
```

Shows:
```sh
Error on line 1, column 1: expected a glob.
  ╷
1 │ 
  │ ^
  ╵
```

**Steps To Reproduce**

1. Run `very_good packages get -r --ignore=""` in a valid directory

**Expected Behavior**
To accept an empty string as input.

**Additional Context**
Would simplify [feat/support-excluding-directories](https://github.com/VeryGoodOpenSource/very_good_workflows/pull/110) default parameter.

### PR DESCRIPTION
**Pull request by alestiago**
## Description

Resolves #703 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: lib/src/cli/cli.dart [hunk 1]
```diff
@@ -176,9 +176,7 @@ extension _Set on Set<String> {
     if (segments.intersection(this).isNotEmpty) return true;
 
     for (final value in this) {
-      if (Glob(value).matches(entity.path)) {
-        return true;
-      }
+      return value.isNotEmpty && Glob(value).matches(entity.path);
     }
```
Comment (wolfenrain) [inline lib/src/cli/cli.dart:180]: This wont ever loop over multiple values, as it will return on the first loop. That is why we had the `if` statement there.

Comment (alestiago) [reply lib/src/cli/cli.dart]: Indeed, thanks for noticing it! Completely forgot space-separated globs are accepted.

**Review by wolfenrain — APPROVED** [review]
