### PR TITLE
fix(test): output random seed when specified

### LINKED ISSUE #335: feat: show the randomization seed for very_good test command
**Description**
I would like to be able to see the seed passed to the `very_good test` command.

**Steps To Reproduce**

1. Run `very_good test --coverage --test-randomize-ordering-seed random`

**Expected Behavior**

My expected output would be:

```
very_good test --coverage --test-randomize-ordering-seed random
Running "flutter test" in /Users/dominik/Projects/app with --test-randomize-ordering-seed=1707931679
```

where `1707931679` is the used seed.

**Additional Context**
`very_good_workflow` displays the seed by default

### PR DESCRIPTION
**Pull request by felangel**
## Description

- fix(test): output random seed when specified (closes #335)

```sh
$ very_good test --test-randomize-ordering-seed random        
Shuffling test order with --test-randomize-ordering-seed=4033303807
Running "flutter test" in my_app...
✓ Optimizing tests (1.5s)
```

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: lib/src/commands/test/test.dart [hunk 1]
```diff
@@ -113,6 +116,9 @@ This command should be run from the root of your Flutter project.''',
     final excludeFromCoverage = _argResults['exclude-coverage'] as String?;
     final randomOrderingSeed =
         _argResults['test-randomize-ordering-seed'] as String?;
+    final randomSeed = randomOrderingSeed == 'random'
+        ? Random().nextInt(4294967295).toString()
```
Comment (erickzanardo) [inline lib/src/commands/test/test.dart:120]: Just curious, can't we just call nextInt with passing a limit?

**Review by erickzanardo — APPROVED** [review]

File: lib/src/commands/test/test.dart (hunk 1 above)
Comment (felangel) [reply lib/src/commands/test/test.dart:120]: What do you mean? Can you provide a suggestion?

Comment (erickzanardo) [reply lib/src/commands/test/test.dart:120]: My bad, I confused this with `nextDouble` which is called without a limit, here we need to pass a limit!
