### PR TITLE
fix: dont crash on test compilation error

### LINKED ISSUE #727: fix: `very_good test` failed (with exception)
```
eseidel@erics-mbp shorebird % very_good test -r    
...
Running "flutter test" in /Users/eseidel/Documents/GitHub/_shorebird/shorebird/bin/cache/flutter/examples...
✓ Optimizing tests (58ms)
Failed to load "/Users/eseidel/Documents/GitHub/_shorebird/shorebird/bin/cache/flutter/examples/api/test/.test_optimizer.dart": type 'FlutterLocalFileComparator' is not a subtype of type 'LocalFileComparator' in type cast
test/.test_optimizer.dart 371:47  _TestOptimizationAwareGoldenFileComparator._goldenFilePaths
test/.test_optimizer.dart 361:27  new _TestOptimizationAwareGoldenFileComparator
test/.test_optimizer.dart 182:26  main

Unhandled exception:
Null check operator used on a null value
#0      _actualTestPath (package:very_good_cli/src/cli/flutter_cli.dart:502:62)
#1      _flutterTest.<anonymous closure> (package:very_good_cli/src/cli/flutter_cli.dart:398:13)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#4      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

I'm not sure what "optimizationApplied" means, but it seems to use a value which is not null-checked:
https://github.com/VeryGoodOpenSource/very_good_cli/blob/main/lib/src/cli/flutter_cli.dart#L502

### PR DESCRIPTION
**Pull request by renancaraujo**
## Description

fix: dont crash on test compilation error 

fixes #727

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: lib/src/cli/flutter_cli.dart [hunk 1]
```diff
@@ -562,6 +568,7 @@ extension on String {
     return '...$truncated';
   }
 
-  String toSingleLine() =>
-      replaceAll('\n', '').replaceAll(RegExp(r'\s\s+'), ' ');
+  String toSingleLine() {
+    return replaceAll('\n', '').replaceAll(RegExp(r'\s\s+'), ' ');
```
Comment (alestiago) [inline lib/src/cli/flutter_cli.dart:572]: Arrow hater?

File: lib/src/cli/flutter_cli.dart [hunk 2]
```diff
@@ -388,16 +388,31 @@ Future<int> _flutterTest({
...
+          // that there is an error when compiling the test optimizer file.
+          if (groups.isNotEmpty) {
+            final topGroupName = _topGroupName(test, groups)!;
+
+            testPath = testPath.replaceFirst(
+              _testOptimizerFileName,
+              topGroupName,
+            );
+
+            testName = testName.replaceFirst(topGroupName, '').trim();
```
Comment (alestiago) [inline lib/src/cli/flutter_cli.dart:412]: I'm a little big confused with what is going on here. This is what I understand:

1. Listen to when we're running the tests and an error occurs
2. If we are running the tests using optimisation then:
2.1. We find the first test that has a non-empty name, sine after each test is done we set the name to empty this is the test group that had the error.
2.2 We then set the suite path to the original path (deduced from the group name which stores the path) in order to log the error clearly to the developer.

Is my understanding correct?

File: lib/src/cli/flutter_cli.dart [hunk 3]
```diff
@@ -493,22 +515,6 @@ String? _topGroupName(Test test, Map<int, TestGroup> groups) => test.groupIDs
...
-        ? path.replaceFirst(_testOptimizerFileName, groupName!)
-        : path;
-
-String _actualTestName(
-  bool optimizationApplied,
-  String name,
-  String? topGroupName,
-) =>
-    optimizationApplied ? name.replaceFirst(topGroupName!, '').trim() : name;
-
```
Comment (alestiago) [inline lib/src/cli/flutter_cli.dart:511]: What's the reasoning behind removing these functions? I see that now we do one less check of `optimizationApplied` is this why?

**Review by alestiago — APPROVED** [review]
