### PR TITLE
fix(test): report errors without throwing

### LINKED ISSUE #392: fix: warnings fail the test
**Description**

If warning occurs during running a test, the very_good test command exits with code 69

e.g. output from GitHub Action:

```
Run very_good test --coverage -x 'presubmit-only' --test-randomize-ordering-seed random
Running "flutter test" in /home/runner/work/org/repo...
Shuffling test order with --test-randomize-ordering-seed=2795804525
Optimizing tests (4.0s)

00:00 ...
00:01 ...
00:02 ...
00:03 ...
00:04 ...
00:05 ...
00:06 ...
00:07 .../opt/hostedtoolcache/.pub-cache/hosted/pub.dartlang.org/
cached_network_image-3.2.0/lib/src/image_provider/cached_network_image_provider.dart:109:29: 
Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.

Error: Process completed with exit code 69.
```

The original warning in cached_network_image is already tracked here: https://github.com/Baseflow/flutter_cached_network_image/issues/732. Nonetheless I think the warning should not fail the step.

**Additional Context**

Affects:
- very_good_cli 0.7.0
- Dart 2.17
- Flutter 3.0.0
- running on macOS and Ubuntu

### PR DESCRIPTION
**Pull request by felangel**
## Description

- fix(test): report errors/warnings without throwing (closes #392)

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by bselwe — APPROVED** [review]

File: lib/src/cli/flutter_cli.dart [hunk 1]
```diff
@@ -379,8 +379,8 @@ Future<int> _flutterTest({
       }
     },
     onError: (Object error, StackTrace stackTrace) {
-      subscription.cancel();
-      completer.completeError(error, stackTrace);
+      stderr('$clearLine$error');
```
Comment (felangel) [inline lib/src/cli/flutter_cli.dart:382]: The test process throws errors for warnings and it turns out we actually don't want to treat those as errors and instead just propagate them to stderr for the user to see without terminating the process.

**Review by wolfenrain — APPROVED** [review]
