### PR TITLE
fix!: license check should exit 0 when no dependencies found

### LINKED ISSUE #1260: fix: license check should not treat lack of dependencies as an error
### Description

If the license checker is run on a package with no direct dependencies it exits with a non-zero exit code (treated as an error). This is not correct behavior imo because if a package has no direct dependencies it should still be considered as passing the license check.

### Steps To Reproduce

1. Create a package with a single internal path dependency
2. Run the license check command
3. Observe the error: `No hosted dependencies found in ./path/to/package of type: direct-main.`

### Expected Behavior

I'd expect the case with no dependencies that match the type to be considered passing since no dependencies means the package isn't violating any licensing rules.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by felangel**
## Status

**READY**

## Description

- fix: license check should exit 0 when no dependencies found (closes #1260)

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved behavior when no hosted dependencies are detected by logging an informational message and returning a success exit code.
- **Tests**
	- Updated test expectations to reflect the adjusted logging, exit status, and command-line usage message order.
	- Enhanced usage string formatting for better readability in test outputs.

### CODE REVIEW

**Comment by felangel** [comment]
FYI @wolfenrain @alestiago @erickzanardo 

e2e tests are failing because the templates need to be updated to fix the synthetic generation deprecation warning for l10n (https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source)

**Comment by wolfenrain** [comment]
> FYI @wolfenrain @alestiago @erickzanardo 
> 
> 
> 
> e2e tests are failing because the templates need to be updated to fix the synthetic generation deprecation warning for l10n (https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source)

Yea that was already on my radar 🫡

**Review by wolfenrain — APPROVED** [review]

**Comment by alestiago** [comment]
Since https://github.com/VeryGoodOpenSource/very_good_cli/pull/1286 the CI should now be all green. There were a few merge conflicts in two test files, I gave a first attempt at quickly resolving them where I could, I'll keep an eye on the pipeline.

File: test/src/commands/create/commands/flutter_plugin_test.dart [hunk 1]
```diff
@@ -29,6 +29,8 @@ class _FakeDirectoryGeneratorTarget extends Fake
     implements DirectoryGeneratorTarget {}
 
 final expectedUsage = [
+  // Exception made for enhanced readability.
+  // ignore: no_adjacent_strings_in_list
```
Comment (alestiago) [inline test/src/commands/create/commands/flutter_plugin_test.dart:33]:
```suggestion
```
